global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'hivepay-queues'
    scrape_interval: 15s
    static_configs:
      - targets: ['queue-monitor:3001']
        labels:
          service: 'hivepay'
          component: 'queue-monitor'

  - job_name: 'hivepay-workers'
    scrape_interval: 15s
    static_configs:
      - targets: ['queue-worker:3001', 'queue-worker-backup:3001']
        labels:
          service: 'hivepay'
          component: 'queue-worker'

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'