global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'hivepay-queues'
    scrape_interval: 15s
    static_configs:
      - targets: ['queue-monitor:3001']
        labels:
          service: 'hivepay'
          component: 'queue-monitor'

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']